#set(CMAKE_MAKE_PROGRAM CACHE FILEPATH "C:/Program Files (x86)/MSBuild/12.0/Bin/MSBuild.exe")

set(DEPS_DIR "C:/Deps/MSVC2015-x64")
#set(glm_DIR "${DEPS_DIR}/???" CACHE PATH "" FORCE)
set(GLM_INCLUDE_DIR "${DEPS_DIR}/glm-0.9.7.4" CACHE PATH "" FORCE)
SET(GPUENGINE_BUILD_TESTS    ON  CACHE BOOL "" FORCE)
SET(GPUENGINE_BUILD_GEPARSER ON  CACHE BOOL "" FORCE)
SET(GPUENGINE_BUILD_GEDE     ON  CACHE BOOL "" FORCE)
